FROM ubuntu

ARG TARGETARCH
ARG TARGETVARIANT

ENV TARGETARCH ${TARGETARCH}
ENV TARGETVARIANT ${TARGETVARIANT}

USER root

RUN apt update && apt -y install python3 python3-yaml python3-pytest iproute2 openssl

VOLUME "/mnt"
WORKDIR /mnt

ENTRYPOINT [ "python3", "-m", "pytest", "./tests" ]
