FROM scratch

ARG TARGETARCH
ARG TARGETVARIANT

COPY --chown=0:0 --chmod=755 dist/server-linux-$TARGETARCH$TARGETVARIANT /server
VOLUME /config

ENTRYPOINT [ "/server" ]
CMD [ "-config=/config/server.yml" ]
