on:
  push:
    tags: '*'

name: Release

jobs:
  test:
    uses: ./.github/workflows/test.yml
  check:
    uses: ./.github/workflows/check.yml

  release:
    runs-on: ubuntu-latest
    needs: test check
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - name: Install slimfat
        run: pip3 install slimfat
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build everything for release
        run: ./build.py --lipo --docker --docker-tag-latest --docker-push --projects wsvpn --architectures arm64,armv7,386,amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
