on:
  push:
    tags: ["*"]

name: Release

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2

  release:
    needs: [test, check, create_release]
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps: 
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install required Python packages
        run: pip install -r requirements.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: matrix.os != 'macos-latest'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build everything for release
        run: python ./build.py --lipo --docker --docker-tag-latest --docker-push --projects wsvpn --platforms local --architectures arm64,armv6,386,amd64

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: dist/*
